main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
	path('', views.home, name='home'),

	path('contact/add', views.contact_view, name='contact_add'),
]

tim/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main.urls', namespace='main')),
    path('admin/', include('tim_admin.urls', namespace='tech')),
    path('django_admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tim_admin/urls.py
from django.urls import path

from . import views

app_name = 'tech'

urlpatterns = [
    path('', views.home, name="home"),
    path('courses/', views.course, name="course"),
    path('teachers/', views.teacher, name="teacher"),
    path('faqs/', views.faq, name="faq"),
    path('galleries/', views.gallery, name="gallery"),
    path('contacts/', views.contact, name="contact"),
    path('settings/', views.settings, name="settings"),
    path('login/', views.admin_login, name="login"),
    path('logout/', views.admin_logout, name="logout"),
    path('set_false/', views.set_false, name="set_false"),
    path('search/', views.search, name='search'),

    path('courses/edit/<int:pk>/', views.courseedit, name="course_edit"),
    path('courses/delete/<int:pk>/', views.coursedelete, name="course_delete"),

    path('teachers/edit/<int:pk>/', views.teacheredit, name="teacher_edit"),
    path('teachers/delete/<int:pk>/', views.teacherdelete, name="teacher_delete"),

    path('faqs/edit/<int:pk>/', views.faqedit, name="faq_edit"),
    path('faqs/delete/<int:pk>/', views.faqdelete, name="faq_delete"),

    path('galleries/edit/<int:pk>/', views.galleryedit, name="gallery_edit"),
    path('galleries/delete/<int:pk>/', views.gallerydelete, name="gallery_delete"),

    path('contacts/pin/<int:pk>/', views.contactpin, name="contact_pin"),
    path('contacts/delete/<int:pk>/', views.contactdelete, name="contact_delete"),
]

templates/tech_admin/contact.html
{% extends 'tech_admin/tech_wrapper.html' %}

{% block content %}

<div style="margin-top: 20px;" class="container">
    {% if contacts.exists %}
    <h1 style="margin-top: 30px;">
        Contacts
    </h1>
    {% else %}
    <h1 style="margin-top: 30px;text-align: center">
        There is no contact
    </h1>
    {% endif %}

    {% for contact in contacts %}
    <div style="position: relative;" class="messages">
        <div class="row">
            <div class="sms">
                <div class="top" style="position: relative;">
                    <h1>
                        {{ contact.name }} {{ contact.surname }}
                    </h1>
                    <div style="margin-left: 30px;margin-top: 5px;">
                        <p>
                            <b>User ID:</b> <span>{{ contact.uuid }}</span>
                        </p>
                    </div>
                </div>
                <div class="bottom">
                    <p>
                        <strong>
                            Phone:
                        </strong>
                        <a href="tel:{{ contact.phone }}">{{ contact.phone }}</a>
                    </p>
                    <p>
                        <strong>
                            Phone 2:
                        </strong>
                        <a href="tel:{{ contact.phone2 }}">{{ contact.phone2 }}</a>
                    </p>
                    <p>
                        <strong>
                            Message:
                        </strong>
                        {{ contact.message }}
                    </p>
                </div>
                <div class="footer">
                    <div>
                        <span>
                            Time:
                        </span>
                        <span>
                            {{ contact.created_at }}
                        </span>
                    </div>
                    <div>
                        <a href="{% url 'tech:contact_pin' contact.id %}" style="margin-right: 20px">
                            <i class="fas fa-pen"></i>
                        </a>
                        <a href="{% url 'tech:contact_delete' contact.id %}" style="margin-right: 10px">
                            <i class="fas fa-trash"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <!-- pinned -->
    {% if pinneds.exists %}
    <h1 style="margin-top: 30px;">
        Pinned Contacts
    </h1>
    {% else %}
    <h1 style="margin-top: 30px;text-align: center">
        There is no pinned contact
    </h1>
    {% endif %}

    {% for contact in pinneds %}
    <div style="position: relative;" class="messages">
        <div class="row">
            <div class="sms">
                <div class="top" style="position: relative;">
                    <h1>
                        {{ contact.name }} {{ contact.surname }}
                    </h1>
                    <div style="margin-left: 30px;margin-top: 5px;">
                        <p>
                            <b>User ID:</b> <span>{{ contact.uuid }}</span>
                        </p>
                    </div>
                </div>
                <div class="bottom">
                    <p>
                        <strong>
                            Phone:
                        </strong>
                        <a href="tel:{{ contact.phone }}">{{ contact.phone }}</a>
                    </p>
                    <p>
                        <strong>
                            Phone2:
                        </strong>
                        <a href="tel:{{ contact.phone2 }}">{{ contact.phone2 }}</a>
                    </p>
                    <p>
                        <strong>
                            Message:
                        </strong>
                        {{ contact.message }}
                    </p>
                </div>
                <div class="footer">
                    <div>
                        <span>
                            Time:
                        </span>
                        <span>
                            {{ contact.created_at }}
                        </span>
                    </div>
                    <div>
                        <a href="{% url 'tech:contact_pin' contact.id %}" style="margin-right: 20px">
                            <div class="fas fa-pin"></div>
                        </a>
                        <a href="{% url 'tech:contact_delete' contact.id %}" style="margin-right: 10px">
                            <div class="fas fa-trash"></div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>


{% endblock %}

templates/tech_admin/courses.html
{% extends 'tech_admin/tech_wrapper.html' %}

{% block title %}Course |{% endblock %}

{% block content %}
{% if courses %}
<div style="display: flex; justify-content: flex-end; padding: 20px;" class="end line">
    <a href="#" class="link" id="edit">
        edit
    </a>
    <div class="icon" id="edit1">
        <i class="fas fa-edit"></i>
    </div>
</div>
{% else %}
<h1 style="margin-top: 100px; text-align: center;">You haven't courses yet.</h1>
{% endif %}
<div class="container">
    <div class="cards">
        {% for course in courses %}
        <div class="card">
            <div class="img top header">
                <img src="{{ course.image.url }}" alt="Course Image">
                <a href="{% url 'tech:course_delete' course.id %}">
                    <div class='icon' style="margin-top: 10px;margin-right: 10px">
                        <i class="fas fa-trash"></i>
                    </div>
                </a>
                <a href="{% url 'tech:course_edit' course.id %}">
                    <div class='icon' style="margin-right: 60px;margin-top: 10px">
                        <i class="fas fa-pen"></i>
                    </div>
                </a>
            </div>
            <div class='content'>
                <div class='_title'>
                    <span>{{ course.course_name }}</span>
                </div>
                <div class="_descripton">
                    <span>{{ course.about }}</span>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

    <center style='margin-top: 50px'>
        <button class="btn padding" id="open">
            <span>Add course</span>
        </button>
    </center>
</div>
<div class="modal">
    <div class="box" style="display: none; height: auto;">
        <div style="position: relative;" class="title">
            <span>Add course</span>
            <div type="button" style="position: absolute; right: 0px; top: 0px;">
                <span class="fas fa-times" id="hide"></span>
            </div>
        </div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div>
                {{ form }}
            </div>
            <div>
                <div>
                    <input type="submit" value="Add course" class="padding btn">
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock %}

{% block script %}
<style>
    label {
        margin-top: 20px;
    }
</style>
<script>
    $('#edit, #edit1').on('click', function () {
        if ($('#edit').text() == 'cancel') $('#edit').text('edit')
        else $('#edit').text('cancel')
        $('.card').toggleClass('onDelete')
    })
</script>
{% endblock %}

templates/tech_admin/delete.html
{% extends 'tech_admin/index.html' %}

{% block modal %}

<style>
    .black-window {
        top: 0;
        left: 0;
        width: 100%;
        height: 100vh;
        display: flex;
        overflow: auto;
        position: fixed;
        color: #000000;
        align-items: center;
        justify-content: center;
        background: rgba(0, 0, 0, 0.7);
    }
    .black-window .white-card {
        width: 50%;
        height: auto;
        display: flex;
        background: #fff;
        border-radius: 10px;
        align-items: center;
        justify-content: center;
        flex-direction: column;
        padding: 50px 50px 20px 50px;
    }
    .button-white {
        color: #000;
        padding: 14px 30px;
        background: #eee;
        border-radius: 10px;
    }
    .button-red {
        padding: 12px 30px;
        color: #fff;
        background: red
    }
    .img-100-100 {
        width: 100%;
        display: block;
        margin: 20px 0;
        border-radius: 20px;
    }
</style>

<div class="black-window">
    <div class="white-card">
        <h1 style="text-align: center">Hey Really Do You Want To Delete {{ obj }} ?</h1>
        <div class="divider"></div>
        <form method="post">
            {% csrf_token %}
            {% if obj.image %}
                <img src="{{ obj.image.url }}" class="img-100-100" alt="">
            {% endif %}
            <a href="{% url 'tech:home' %}" class="button-white">Cancel</a>
            <button class="button-red">Delete</button>
        </form>
    </div>
</div>


{% endblock %}

templates/tech_admin/faq.html
{% extends 'tech_admin/tech_wrapper.html' %}

{% block content %}

<style>
    label {
        margin-top: 20px;
    }
</style>

<div style="padding: 20px;" class="end line">
    <a href="#" class="link" id="edit">
        Edit
    </a>
    <div class="icon" id="edit1">
        <i class="fas fa-edit"></i>
    </div>
</div>
<div class="container">
    <div class="faqs">
        <div class="row">
            <!-- FAQ item -->
            {% for faq in faqs %}
            <div class="faq">
                <div class="faq-question">
                    <span>{{ faq.question }}</span>
                    <a href="{% url 'tech:faq_delete' faq.id %}">
                    <div class='icon'>
                            <i class="fas fa-trash"></i>
                        </div>
                    </a>
                    <a href="{% url 'tech:faq_edit' faq.id %}">
                    <div class='icon' style="margin-right: 50px;">
                        <i class="fas fa-pen"></i>
                    </div>
                </a>
                </div>
                <div class="faq-answer">
                    <span>{{ faq.answer }}</span>
                </div>
            </div>
            {% endfor %}
            <!-- /FAQ item -->
        </div>
    </div>
    <center style='margin-top: 30px;'>
        <button class="btn padding" id="open">
            <span>Add FAQ</span>
        </button>
    </center>
</div>

<div class="modal">
    <div class="box" style="display: none; height: auto">
        <div style="position: relative;" class="title">
            <span>FAQ</span>
            <div type="button" style="position: absolute; right: 0px; top: 0px;">
                <span class="fas fa-times" id="hide"></span>
            </div>
        </div>
        <form method="post">
            {% csrf_token %}
            <div>
                {{ form }}
            </div>
            <div>
                <div>
                    <input type="submit" value="Add FAQ" class="padding btn">
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock %}

{% block script %}
<script>
    $('#edit, #edit1').click(function () {
        if ($('#edit').text() == 'cancel') $('#edit').text('edit')
        else $('#edit').text('cancel')
        $('.faqs .faq').toggleClass('onDelete');
    });
</script>
{% endblock %}

templates/tech_admin/gallery.html
{% extends 'tech_admin/tech_wrapper.html' %}

{% block content %}
<div style="padding: 20px;" class="end line">
    <a href="#" class="link" id="edit">
        edit
    </a>
    <div class="icon" id="edit1">
        <i class="fas fa-edit"></i>
    </div>
</div>
<div class="container gallery">
    <div class="row" style="display: flex;flex-wrap: wrap;justify-content: space-around">
        <!-- gallery Item -->
        {% for photo in photos %}
        <div class="col">
            <img src="{{ photo.photo.url }}">
            <a href="{% url 'tech:gallery_delete' photo.id %}">
                <div class='icon' style="margin-top: 10px;margin-right: 60px">
                    <i class="fas fa-trash"></i>
                </div>
            </a>
            <a href="{% url 'tech:gallery_edit' photo.id %}">
                <div class='icon' style="margin-right:5px;margin-top: 10px">
                    <i class="fas fa-pen"></i>
                </div>
            </a>
        </div>
        {% endfor %}
        <!-- /gallery Item -->

    </div>
</div>
<center>
    <button class="btn padding" id="open">
        <span>Add photo</span>
    </button>
</center>

<div class="modal">
    <div class="box" style="display: none; height: auto;">
        <div style="position: relative;" class="title">
            <span>Photo</span>
            <div type="button" style="position: absolute; right: 0px; top: 0px;">
                <span class="fas fa-times" id="hide"></span>
            </div>
        </div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div>
                {{ form }}
            </div>
            <div>
                <div>
                    <input type="submit" value="Add photo" class="padding btn">
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock %}

{% block script %}
<script>
    $('#edit, #edit1').click(function () {
        if ($('#edit').text() == 'cancel') $('#edit').text('edit')
        else $('#edit').text('cancel')
        $('.gallery .col').toggleClass('onDelete');
    });
</script>
{% endblock %}

templates/tech_admin/search.html
{% extends 'tech_admin/tech_wrapper.html' %}


{% block content %}

	<h1 style="text-align: center;margin-top: 30px">
		Search results for '{{ key }}'
	</h1>
	<div style="display: flex; justify-content: flex-end; padding: 20px;" class="end line">
    <a href="#" class="link" id="edit">
        Edit
    </a>
    <div class="icon" id="edit">
        <svg width="20px" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><!--! Font Awesome Free 6.0.0-beta2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License) --><path d="M497.9 74.16L437.8 14.06c-18.75-18.75-49.19-18.75-67.93 0l-56.53 56.55l127.1 128l56.56-56.55C516.7 123.3 516.7 92.91 497.9 74.16zM290.8 93.23l-259.7 259.7c-2.234 2.234-3.755 5.078-4.376 8.176l-26.34 131.7C-1.921 504 7.95 513.9 19.15 511.7l131.7-26.34c3.098-.6191 5.941-2.141 8.175-4.373l259.7-259.7L290.8 93.23z"/></svg>
    </div>
</div>

<div class="container">
    <div class="cards">
        {% for course in courses %}
        <div class="card">
            <div class="img top header">
                <img src="{{ course.image.url }}" alt="Course Image">
                <div class='icon' style="margin-top: 10px;margin-right: 10px">
                    <a href="{% url 'tech:course_delete' course.id %}">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><!--! Font Awesome Free 6.0.0-beta2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License) --><path d="M53.21 467c1.562 24.84 23.02 45 47.9 45h245.8c24.88 0 46.33-20.16 47.9-45L416 128H32L53.21 467zM432 32H320l-11.58-23.16c-2.709-5.42-8.25-8.844-14.31-8.844H153.9c-6.061 0-11.6 3.424-14.31 8.844L128 32H16c-8.836 0-16 7.162-16 16V80c0 8.836 7.164 16 16 16h416c8.838 0 16-7.164 16-16V48C448 39.16 440.8 32 432 32z"/></svg>
                    </a>
                </div>
                <div class='icon' style="margin-right: 60px;margin-top: 10px">
                    <a href="{% url 'tech:course_edit' course.id %}">
                        <svg width="20px" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><!--! Font Awesome Free 6.0.0-beta2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License) --><path d="M497.9 74.16L437.8 14.06c-18.75-18.75-49.19-18.75-67.93 0l-56.53 56.55l127.1 128l56.56-56.55C516.7 123.3 516.7 92.91 497.9 74.16zM290.8 93.23l-259.7 259.7c-2.234 2.234-3.755 5.078-4.376 8.176l-26.34 131.7C-1.921 504 7.95 513.9 19.15 511.7l131.7-26.34c3.098-.6191 5.941-2.141 8.175-4.373l259.7-259.7L290.8 93.23z"/></svg>
                    </a>
                </div>
            </div>
            <div class='content'>
                <div class='_title'>
                    <span>{{ course.course_name }}</span>
                </div>
                <div class="_descripton">
                    <span>{{ course.about }}</span>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

<div class="container">
    <div class="faqs">
        <div class="row">

            <!-- FAQ item -->
            {% for faq in faqs %}
            <div class="faq">
                <div class="faq-question">
                    <span>{{ faq.question }}</span>
                    <div class='icon'>
                        <a href="{% url 'tech:faq_delete' faq.id %}">
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><!--! Font Awesome Free 6.0.0-beta2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License) --><path d="M53.21 467c1.562 24.84 23.02 45 47.9 45h245.8c24.88 0 46.33-20.16 47.9-45L416 128H32L53.21 467zM432 32H320l-11.58-23.16c-2.709-5.42-8.25-8.844-14.31-8.844H153.9c-6.061 0-11.6 3.424-14.31 8.844L128 32H16c-8.836 0-16 7.162-16 16V80c0 8.836 7.164 16 16 16h416c8.838 0 16-7.164 16-16V48C448 39.16 440.8 32 432 32z"/></svg>
                        </a>
                    </div>
                    <div class='icon' style="margin-right: 50px;">
                        <a href="{% url 'tech:faq_edit' faq.id %}">
                            <svg width="20px" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><!--! Font Awesome Free 6.0.0-beta2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License) --><path d="M497.9 74.16L437.8 14.06c-18.75-18.75-49.19-18.75-67.93 0l-56.53 56.55l127.1 128l56.56-56.55C516.7 123.3 516.7 92.91 497.9 74.16zM290.8 93.23l-259.7 259.7c-2.234 2.234-3.755 5.078-4.376 8.176l-26.34 131.7C-1.921 504 7.95 513.9 19.15 511.7l131.7-26.34c3.098-.6191 5.941-2.141 8.175-4.373l259.7-259.7L290.8 93.23z"/></svg>
                        </a>
                    </div>
                </div>
                <div class="faq-answer">
                    <span>{{ faq.answer }}</span>
                </div>
            </div>
            {% endfor %}
            <!-- /FAQ item -->

        </div>
    </div>
</div>

<div class="container gallery">
    <div class="row" style="display: flex;flex-wrap: wrap;justify-content: space-around">
        <!-- gallery Item -->
        {% for photo in photos %}
        <div class="col">
            <img src="{{ photo.photo.url }}">
            <div class='icon' style="margin-top: 10px;margin-right: 10px">
                <a href="{% url 'tech:gallery_delete' photo.id %}">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><!--! Font Awesome Free 6.0.0-beta2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License) --><path d="M53.21 467c1.562 24.84 23.02 45 47.9 45h245.8c24.88 0 46.33-20.16 47.9-45L416 128H32L53.21 467zM432 32H320l-11.58-23.16c-2.709-5.42-8.25-8.844-14.31-8.844H153.9c-6.061 0-11.6 3.424-14.31 8.844L128 32H16c-8.836 0-16 7.162-16 16V80c0 8.836 7.164 16 16 16h416c8.838 0 16-7.164 16-16V48C448 39.16 440.8 32 432 32z"/></svg>
                </a>
            </div>
            <div class='icon' style="margin-right: 60px;margin-top: 10px">
                <a href="{% url 'tech:gallery_edit' photo.id %}">
                    <svg width="20px" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><!--! Font Awesome Free 6.0.0-beta2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License) --><path d="M497.9 74.16L437.8 14.06c-18.75-18.75-49.19-18.75-67.93 0l-56.53 56.55l127.1 128l56.56-56.55C516.7 123.3 516.7 92.91 497.9 74.16zM290.8 93.23l-259.7 259.7c-2.234 2.234-3.755 5.078-4.376 8.176l-26.34 131.7C-1.921 504 7.95 513.9 19.15 511.7l131.7-26.34c3.098-.6191 5.941-2.141 8.175-4.373l259.7-259.7L290.8 93.23z"/></svg>
                </a>
            </div>
        </div>
        {% endfor %}
        <!-- /gallery Item -->

    </div>
</div>

{% block script %}

<script>
    $('#edit').on('click', function () {
        if ($('#edit').text() == 'cancel') $('#edit').text('edit')
        else $('#edit').text('cancel')
        $('.card').toggleClass('onDelete')

    	if ($('#edit').text() == 'cancel') $('#edit').text('edit')
        else $('#edit').text('cancel')
        $('.faqs .faq').toggleClass('onDelete');
    })
</script>

{% endblock %}

{% endblock %}

templates/tech_admin/teachers.html
{% extends 'tech_admin/tech_wrapper.html' %}

{% block content %}

<style>
    label {
        margin-top: 20px;
    }
</style>

<div style="padding: 20px;" class="end line">
    <a href="#" class="link" id="edit">edit</a>
    <div class="icon" id="edit1">
        <i class="fas fa-edit"></i>
    </div>
</div>
<div style="margin-top: 30px;" class="container">
    <div class="cards">
        <div class="row" style="display: flex;flex-wrap: wrap;justify-content: space-around">

            <!-- Teacher card -->
            {% for teacher in teachers %}
            <div class="card" style="margin: 10px;">
                <div class="top">
                    <div class="img">
                        <img src="{{ teacher.image.url }}" alt="user" style="width: 200px;">
                    </div>
                    <div class="content">
                        <h3>
                            <b>{{ teacher.teacher_name }}</b>
                        </h3>
                    </div>
                    <a href="{% url 'tech:teacher_delete' teacher.id %}">
                    <div class="icon">
                            <i class="fas fa-trash"></i>
                        </div>
                    </a>
                    <a href="{% url 'tech:teacher_edit' teacher.id %}">
                    <div class="icon" style="margin-right: 50px;">
                            <i class="fas fa-pen"></i>
                        </div>
                    </a>
                </div>
                <div class="bottom" style="width: 100%">
                    <p style="text-align:left;">
                        {{ teacher.about }}
                    </p>
                </div>
            </div>
            {% endfor %}

            <!-- /Teacher card -->

        </div>
    </div>
</div>
<center style='margin-top: 30px;'>
    <button class="btn padding" id="open">
        <span>Add teacher</span>
    </button>
</center>

<div class="modal">
    <div class="box" style="display: none; height:  auto;">
        <div style="position: relative;" class="title">
            <span>Add teacher</span>
            <div type="button" style="position: absolute; right: 0px; top: 0px;">
                <span class="fas fa-times" id="hide"></span>
            </div>
        </div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div>
                {{ form }}
            </div>
            <div>
                <div>
                    <input type="submit" value="Add teacher" class="padding btn">
                </div>
            </div>
        </form>
    </div>

</div>
{% endblock %}

{% block script %}
<script>
    $('#edit, #edit1').click(function () {
        if ($('#edit').text() == 'cancel') $('#edit').text('edit')
        else $('#edit').text('cancel')
        $('.card').toggleClass('onDelete');
    });
</script>

{% endblock %}

templates/tech_admin/tech_wrapper.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'assets/css/admin.css' %}" />
    <link rel="shortcut icon" href="{% static 'assets/media/logo/logo.png' %}" type="image/x-icon" />
    <title>{% block title %}{% endblock %} Admin</title>
    <style>
        :is(.faq, .card, .sms) a {
            color: #000;
        }

        :is(.faq, .card, .sms) .icon {
            width: 50px;
            height: 50px;
        }
    </style>
</head>

<body>
    <div class="left-panel collapsed">
        <div class="toggle-panel">
            <div class="logo">
                <a href="/">Admin</a>
            </div>
            <div class="toggler">
                <div class="toggler-icon">
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
            </div>
        </div>
        <div class="link-list">
            <ul ionic class="list">
                <li icon="panel" class="item active">
                    <a href="{% url 'tech:home' %}">Admin</a>
                </li>
                <li icon="course" class="item">
                    <a href="{% url 'tech:course' %}">Courses</a>
                </li>
                <li icon="teacher" class="item">
                    <a href="{% url 'tech:teacher' %}">Teachers</a>
                </li>
                <li icon="faq" class="item">
                    <a href="{% url 'tech:faq' %}">FAQ</a>
                </li>
                <li icon="gallery" class="item">
                    <a href="{% url 'tech:gallery' %}">Gallery</a>
                </li>
                <li icon="sms" class="item">
                    <a href="{% url 'tech:contact' %}">Contacts</a>
                </li>
                <li icon="settings" class="item">
                    <a href="{% url 'tech:settings' %}">Settings</a>
                </li>
            </ul>
        </div>
    </div>
    <div main class="container open">
        <header>
            <div class="user">
                <div class="user-info">
                    <div class="user-image">
                        <img src="{% static 'assets/images/user.jpg' %}" alt="user" width="100%" />
                    </div>
                    <div class="user-info-name">
                        <p>Welcome</p>
                        <h1 fontsize="24px" style="font-size: 24px">
                            {{ request.user.username }}
                        </h1>
                    </div>
                </div>
            </div>
            <div class="search-panel" style="width: 100%">
                <div class="search-panel-input" style="position: relative">
                    <form method="get" action="{% url 'tech:search' %}">
                        <input type="text" name="key" placeholder="Search..." id="search_input">
                    </form>
                    <script>
                        let input = document.querySelector('#search_input');
                        input.addEventListener('change', () => {
                            console.log('input changed')
                            document.querySelector('form').submit()
                        })
                    </script>
                    <div class="search-modal">
                        <ul class="search-results">
                            <li>
                                <a href="#">result 1</a>
                            </li>
                            <li>
                                <a href="#">result 2</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <a href="{% url 'tech:logout' %}" class="btn padding" style="
              position: absolute;
              top: 30px;
              right: 75px;
              color: #000;
              background: #eee;
              border-radius: 10px;
            ">
                    <i class="fa-solid fa-arrow-right-from-bracket"></i>
                    Logout
                </a>
            </div>
        </header>
        {% block content %} {% endblock %}
    </div>
    
    <script src="{% static 'assets/js/jquery.js' %}"></script>
    <script src="{% static 'assets/js/admin.js' %}"></script>
    {% block script %} {% endblock %}
</body>

</html>